### ISSUE TITLE
It seems that there is no circular logo in the project.

### ISSUE THREAD

**Issue by howie6879** [python-ruia/ruia-assets#1]
Hi:

Thanks for your great job, it seems that there is no circular logo in the project.

![image](https://user-images.githubusercontent.com/17047388/52766139-28718500-3061-11e9-94f3-1175222b5294.png)

**Comment by mirzazulfan** [comment]
Hi @howie6879 , here's all [Files](https://drive.google.com/drive/folders/17yuk7FeoQ03oDU8WeTiIKaqrJcvwJbG1). Best Regard.

**Comment by howie6879** [comment]
@mirzazulfan 
Thanks for your great job~
